### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 5: Monte Carlo Yöntemleri

### ISSUE THREAD

**Issue by ayyucekizrak** [yz-ai/yz-ai.github.io#11]
https://yz-ai.github.io/blog/pekistirmeli-ogrenme/monte-carlo-yontemleri-bolum-5
**Pekiştirmeli Öğrenme - Bölüm 5: Monte Carlo Yöntemleri**

---

**Eylem Değerlerinin Monte Carlo Tahmini başlığı için:**
1. MC denmeye başlanmış Monte Carlo için baka bişeymiş gibi anlaşılmaması için son kez Monte Carlo'yu açıkça yazdığınız yere **(MC)** kısaltmasını parantez içinde eklerseniz. Devamı daha anlaşılır olur.

**Monte Carlo Kontrolü başlığı için:**
1. İlk paragrafın ardından kitaptaki evalution-improvement şeklini ve 5.1 denklem akışını vermekte fayda var. 
2. Bu başlıkta yine 'Monte Carlo' demeye başlıyoruz. Karar verelim ya MC ile devam edelim ya da Monte Carlo yazalım.

**Keşfi Başlatmadan Monte Carlo Kontrolü başlığı için:**
1.  _Bu bölümde yöntem olarak, açgözlü (ε-greedy) kullanılacaktır çünkü, genellikle tahmini maksimum eylem değerine sahip olanı seçtikleri içindir._  
Bu cümleyi şu şekilde yeniden yazıyorum: "Bu bölümde; genellikle tahmini maksimum eylem değerine sahip olanı seçtikleri için açgözlü (ε-greedy) yöntem olarak kullanılacaktır. "
2. Son paragrafın ilk cümlesinde **v∗  la**  denen yeri **v∗  ile** diye düzeltmekte fayda var.

**Önem Örneklemesi ile Politika Dışı Tahmin (Off-Policy Prediction via Importance Sampling) başlığı için:**
1. Politika-dışı  yazarken araya - işaretini koyuyorsak hep koyalım. Bir koyup bir koymamazlık yapmayalım.
2.  4. paragrafın son cümlesinde (gre-açgözlü) yanlış mı yazılmış?
3. _Aksine, sıradan önem-örnekleme tahmincisinin (5.5) ilk ziyaret versiyonu, beklenti içinde her zaman vπ(s) olur, fakat bu aşırı olabilir._ Şeklinde bir cümle var **(5.5)** denklemi bu cümlenin üstünde yazıyor ama onun 5.5 olduğunu anlamak için kitaba bakmak gerekiyor. Bu yüzden **V(s)** denklemi diye düzeltebiliriz.
4. _önem-örneklemesi_ arasında **-** bir var bir yok. Ona da karar vermek lazım.

**Politika Dışı Monte Carlo Kontrol (Off-policy Monte Carlo Control) başlığı için:** 
1. Yine Monte Carlo ve MC ler uçuşuyor.
2. _%Burada bir resim mevcut istenirse alt bölüm ve o resim eklenilecekti._ diye bir ekleme yapılmış ama resim eklenmemiş durumda.
3. Daha önce Examles lara Örnek demiştiniz şimdi Alıştırma dediniz. Onları da tek dile çevirmek gerek. 

---
Elinize sağlık bu bölüm için bu kadar düzeltme şimdilik yeter.

**Comment by eralpozcan** [comment]
- Eylem Değerlerinin Monte Carlo Tahmini 
 - [x] 1. Madde : _Hepsi Monte Carlo yapıldı._

- Monte Carlo Kontrolü 
 - [ ] 1. Madde : _Çevirisi yapılıp,eklemesi yapıldı._
 - [x] 2. Madde : _Hepsi Monte Carlo yapıldı._
 - [x] İlave : _Farklı yerlerde bahsi geçen Örnek 5.1 Eklendi._

-  Keşfi Başlatmadan Monte Carlo Kontrolü 
 - [x] 1. Madde : _Değiştirildi._
 - [x] 2. Madde :  _Düzeltildi._
-  Önem Örneklemesi ile Politika Dışı Tahmin
  - [x] 1. Madde : _Artık hepsi Politika-Dışı olarak geçiyor._
  - [x] 2. Madde : _(ε-açgözlü) olarak güncelledim. {ε-greedy} olarak değiştirilebilir._
  - [x] 3. Madde : _(5.5) Eklendi_
  - [x] 4. Madde : _Düzenlendi_
- Politika Dışı Monte Carlo Kontrol (Off-policy Monte Carlo Control) 
 - [x] 1. Madde :  _Hepsi artık Monte Carlo_
 - [x] 2. Madde :  _Eklenip düzenlendi._
 - [x] 3. Madde :   _"Örnek" olarak tek dile çevrildi._

**Comment by eralpozcan** [comment]
Düzeltmeler yapılıp daha sonra yapılacak düzeltmeler için #34 açıldığından kapatıyorum.

**Comment by 160202049** [comment]
merhaba ayyüce hanım paylaşmış olduğunuz bilgiler çok güzel ve öğretici ama ne yazık ki kaynağını göremedim :( yardımcı olursanız sevinirim @ayyucekizrak

**Comment by kivancguckiran** [comment]
@160202049 Merhaba, burası Yapay Zeka Araştırma İnisiyatifi grubunun web sitesini düzenlemek için açıldı. Henüz paylaşımlarını yapmadık, ama siteye şuradan erişebilirsiniz:  https://yz-ai.github.io/
