### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 6: Temporal-Difference (Zamansal Fark) Öğrenmesi

### ISSUE THREAD

**Issue by ayyucekizrak** [yz-ai/yz-ai.github.io#12]
https://yz-ai.github.io/blog/pekistirmeli-ogrenme/temporal-difference-zamansal-fark-ogrenmesi-bolum-6
---

**Temporal-Difference (Zamansal Fark) Öğrenmesi başlığı için:**
1. "Pekiştirmeli öğrenmenin **en** temel yöntemlerinden biri olan zamansal fark öğrenmesi, daha önceki bölümlerde gördüğümüz dinamik programlama ve Monte Carlo yöntemlerinin bir çeşit kombinasyonudur. " cümlesinde **en** kelimesini kaldırmalıyız.

**Zamansal Fark Öğrenmesinde Öngörü Problemi başlığı için:** 
1. kitapta şekil 6.1 deki örnek belki bu başlık altına eklenebilir (bu sadece öneri laflar ve denklemler daha anlaşılır olur, zamanla da eklenebilir acil bişey değil)

**Tahmin probleminde Zamansal Fark Öğrenmesinin Avantajları başlığı için:**
1. İlk paragraftaki şu cümleyi  _Dinamik programlamaya karşı en büyük artısı açıkça görülebileceği gibi zamansal fark öğrenmesi yöntemlerinin ortamın modeline ihtiyaç duymamasıdır._  yeniden yazıyorum: _"Zamansal fark öğrenme açıkça görülebileceği gibi ortamın modeline ihtiyaç duymamaktadır. Bu özelliği dinamik programlamaya göre en önemli avantajıdır."_
2.  Örnek 6.2 hakkında birkaç cümle daha eklenip diğer iki şekilde eklenebilir. Şuan mevcut grafikte bölüm sayısı ne vs net anlaşılmıyor. 

**Zamansal Fark Öğrenmesinin En Uygunluğu (Optimality) başlığı için:**
1. **batch** kelimesini genelde **küme / paket ** olarak kullanıyoruz ama emin olamadım.

**Zamansal Fark Öğrenmesiyle Politikalı (On-policy) Kontrol başlığı için:**
1. Bu başlığın başında **Sarsa** da desek olmaz mı kitaba uygun olarak.

**Q-Öğrenmesi: Zamansal Fark Öğrenmesiyle POlitikasız (Off-policy) Kontrol başlığı için:**
1. Bu başlıktaki ilk örnek eklense harika olur. Bu haliyle anlaşılır ama örnekle daha güzel olur. Zamanla eklenecekler içinde de kalabilir.

**Beklentili (Expected) Sarsa başlığı için:**
1. şekil 6.3 ü de eklersek harika olur.

**En Büyütme (Maximization) Sorunu ve İkili Öğrenme (Double Learning) başlığı için:** 
1. "ençoklama" kelimesinin yanına parantez içinde sadece ilkinde (maksimizasyon) yazabiliriz.
2. ikinci paragrafın ilk cümlesinde **"Ençoklama işleminin neden sorun olduğunu anlamak için bir örnek verelim."** dedikten sonraki cümle **Örneğin** kelimesi ile başlamasın. Direkt başlasın.
3. **En büyütme** diye bir kavram geçiyor. Bu **ençoklama** ile aynı şeyse aynı şekilde yazılmalı.

gerisi okay! 👍

**Comment by eralpozcan** [comment]
- Temporal-Difference (Zamansal Fark) Öğrenmesi
 - [x] 1. Madde : 

- Zamansal Fark Öğrenmesinde Öngörü Problemi 
 - [x] 1. Madde : _ Çevirisi yapılıp,eklemesi yapıldı._

-  Tahmin probleminde Zamansal Fark Öğrenmesinin Avantajları
 - [x] 1. Madde : _Değiştirildi._
 - [x] 2. Madde :  _Düzeltildi._

-  Zamansal Fark Öğrenmesinin En Uygunluğu (Optimality)
  - [x] 1. Madde : _Sözlükte yığın olarak geçtiğinden ötürü öyle yazılmış nihai karar sonrası güncellenecek._

- Zamansal Fark Öğrenmesiyle Politikalı (On-policy) Kontrol
 - [x] 1. Madde :  _Güncellendi_

- Q-Öğrenmesi: Zamansal Fark Öğrenmesiyle Politikasız (Off-policy) Kontrol
 - [x] 1. Madde :  _İlk Örnek eklenecek._

- Beklentili (Expected) Sarsa
 - [x] 1. Madde :  _Türkçeleştirilip eklendi._

- En Büyütme (Maximization) Sorunu ve İkili Öğrenme (Double Learning)
 - [x] 1. Madde :  _Güncellendi_
 - [x] 2. Madde :  
 - [x] 3. Madde :

**Comment by yavuzKomecoglu** [comment]
Tamamlandığı için kapatıyorum.
https://github.com/yz-ai/yz-ai.github.io/pull/26
