### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 4: Dinamik Programlama

### ISSUE THREAD

**Issue by FurkanArslan** [yz-ai/yz-ai.github.io#13]
"Dinamik Programlama terimi (Dynamic Programming-DP), bir Markov Karar Süreci (Markov Decision Process) ortamının mükemmel bir modelinde en uygun politikayı (optimal policy) hesaplama amacı ile kullanılacak algoritmaların bütününü ifade eder. "

1. Biraz google translate çevirisi gibi olmuş sanki :) Çünkü kitapta yazan cümle ile burada yazılanlar arasında bazı yanlışlıklar var gibi.
2. Cümlesinde çok fazla parantez içerisinde Ingilizce terimi kullanmışız. Okumayı çok zorlaştırıyor.
3. "en" kelimesi olmasa daha iyi gibi
---

"DP’nin ve genel olarak Pekiştirmeli Öğrenmenin temel fikri, iyi bir politika arayışını organize etmek ve yapılandırmak için değer fonksiyonların kullanmasıdır."

1. fonksiyonların**ın**
2. kitapta "**good policies**" yazıyor, burada bir politika yazılmış. Burada da çoğul olmalı gibi.

---

"Daha önce bahsedildiği gibi, burada Bellman Uygunluk Denklemleri ile en uygun değer fonksiyonları bulunur."

1. "Daha önce bahsedildi" yerine kitapta yazana benzer bir yaklaşım kullanılabilir. Mesela  "Chapter 3'te bahsedildiği gibi" ya da "Bölüm 3: Sonlu Markov Karar Süreçlerinde bahsedildiği gibi" denirse daha güzel olur. Hatta Bölüm 3'e link bile verilebilir.
2. Bu cümleden denkleme geçiş yapamıyorum. Arada bir kopukluk var gibi. Kitapta aşağıdaki gibi bir cümle var.

> In this chapter we show how DP can be used to compute the value functions defined in Chapter 3. As discussed there, we can easily obtain optimal policies once we have found the optimal value functions, v* or q*, which satisfy the Bellman optimality equations.

- Bu tarz bir bağlantı cümlesi ile formüle geçmek bana daha mantıklı geldi. Yoksa formülde olan v* ne q* ne gibi sorular oluşuyor.
--- 

"Politika Değerlendirmesi (Tahmin)" bölümündeki ilk formülde:

1- for all s \in S, formülün önemli bir parçası onu da koymamız gerek.
2- Bir de bu formül niye kaymış yahu. satırlar birbirine girmiş gibi.

---

"Değer fonksiyonları, daha iyi politikalar geliştirmeye yardımcı olmak amacıyla geliştirilmektedir. Herhangi bir fonksiyon için rastgele belirlenen bir politikaya göre, s durumunun ne kadar iyi bir durum olduğu bilinmeye çalışılacaktır. Bunu öğrenmenin yolu s  durumunda a  eylemini uygulayarak mevcut π  politikasını takip etmektir"

1. Burada **state** s ve **action** a demek daha anlamlı gibi.
2. Herhangi bir fonksiyonun değil belirli bir fonksiyon için olmalı sanki. Kitapta şöyle yazıyor çünkü:

> Suppose we have determined the value function v(π) for an arbitrary deterministic policy π.

---

"Bu gelişimler şu şekilde gösterilir."

1. Nokta değil iki nokta üst üste :)

---

**Politika İterasyonu**

1. Bu bölümde kullanılan resmin hiç açıklaması yok. Baya havada kalmış öyle. En azından kitapta resmin altında yazan yorumu koyabiliriz. Hem politika iterasyonuna bir örnek de vermiş oluruz bu şekilde. Daha kafada oturur gibi.

> Figure 4.1: Convergence of iterative policy evaluation on a small gridworld. The left column is
the sequence of approximations of the state-value function for the random policy (all actions
equally likely). The right column is the sequence of greedy policies corresponding to the value
function estimates (arrows are shown for all actions achieving the maximum, and the numbers
shown are rounded to two signicant digits). The last policy is guaranteed only to be an
improvement over the random policy, but in this case it, and all policies after the third iteration,
are optimal.

2. Kitapta politika iterasyonunun algoritması da var. Onu da buraya eklesek güzel olmaz mıydı acaba?

---

**Value Iteration**

- Burada da bir algoritma var. Bunu da aynı politika iterasyonu gibi eklesek mi acep?

---

"Şu ana kadar bahsedilen DP yöntemlerinin önemli bir dezavantajı, MDP’nin tüm durum kümesi üzerinde çalışıyor olması olabilir"

- Bu cümledeki "olabilir" kelimesini kaldırsak daha iyi olabilir. 

---

"Bazı değerler birden çok kez güncellenebilse dahi, bu yapı hızlı yakınsama sağlayabilir."

- Bu cümlede bir düşüklük var. "güncellense dahi" mi denilmek istenildi acaba?

**Comment by eralpozcan** [comment]
**- Dinamik Programlama**
 - [ ] 1. Madde : _Anlam düşüklüğü ve hatalar düzeltildi._
 - [x] 2. Madde : _Terimlerin ilk geçtikleri yerde İngilizcesinin parantez içerisinde gösterme kararı alındığı için aynı bırakıldı._
 - [x] 3. Madde : _"en" kelimesi kaldırıldı._
-- 
 - [x] 1. Madde : _Düzeltildi_
 - [x] 2. Madde : _Cümle çoğul hale getirildi. _**"iyi politikaları arayışını organize etmek..."**__
--
 - [x] 1. Madde : _Düzeltildi. Link yönlendirmesi daha sonra eklenecek_
 - [x] 2. Madde : _Cümle denilen örnekteki gibi daha anlamlı olacak hale getirildi_

**- Politika Değerlendirmesi (Tahmin)**
 - [x] 1. Madde : _Eklendi_
 - [x] 2. Madde : _Güncellemesi gönderilmediği için öyle kalmış. Son sürümünde düzgün. Sıralı olarak gözükecek._

**-Politika Geliştirme**
 - [x] 1. Madde : _İngilizceleri Türkçe kelimenin yanında parantez içerisinde gösterildi._
 - [x] 2. Madde : _Düzeltildi._

**-Politika İterasyonu**
- [x] 1. Madde : _":" Kısmı düzeltildi._
- [x] 2. Madde : _Şekil:4.1'in açıklaması eklendi._
- [x] 3. Madde : _Algoritma geçici olarak İngilizce haliyle eklendi._

**-Value Iteration**
- [x] 1. Madde : _Algoritma geçici olarak İngilizce haliyle eklendi._

**- Asenkron Dinamik Programlama**
 - [x] 1.Madde : _Düzeltildi_

**Comment by eralpozcan** [comment]
Tamamlanıp,eksikler için yenisi açıldığından kapatıyorum. #30
