### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 7: n-Adım Paketleme

### ISSUE THREAD

**Issue by ayyucekizrak** [yz-ai/yz-ai.github.io#15]
https://yz-ai.github.io/blog/pekistirmeli-ogrenme/n-adim-paketleme-bolum-7
---

**n-Adım Paketleme başlığı için:**
1. n-step başlıkta olduğu gibi metin içinde de n-adım olarak yazılsa iyi olur **N** kullanılmış onları **n** olarak düzeltmekten bahsediyorum. (cümle başı bile olsa küçük harf olmalı)

**n-Adım TD Tahmini başlığı için:**
1. meblağ diye bir sözcük kullanmışsınız. Onu  tutar/miktar gibi düzeltmek iyi olabilir.
2. figure 7.3 alınmış belki onun açıklaması diğer bölümlerde yaptığınız gibi altına çevrilmeli italik olarak. Önceki bir bölümde öyle yapmıştınız.
3. Şekilden sonraki 2. paragrafta yine "MC" denmiş hepsini açmaya karar verdik sanırım.

**n−step Sarsa başlığı için:**
1. başlıkta step mi diyeceğiz adım mı? hep adım dendi adım diyelim bence.
2. paragraf içinde kitaba atıf olarak şekil numarası veriyoruz ama ya onu belirtmek gerek ya da buradaki şekillere de numara vermek gerek. Mesela (7.1, 7.2, 7.3 ve 7.4 gibi.)

**n− step Politika dışı (Off-Policy) Öğrenme başlığı için:**
1. yine başlıkta **step** demişiz.
2. _Böylece yeni güncellememiz (7.9), daha önceki n-adım TD güncellememizi genelleştirip tamamen değiştirebilir._  diye geçen cümlede kitaptaki 7.9 denklemine atıf yapılıyor denklem özette de yazıyor 7.9 ne diye okuyan anlamaz o yüzden ne denklemiyse adıyla yazılsa ya da _"...güncellememiz **ρt:h** ifadesi, daha önceki..."_ diye de yazılabilir. 
3. aynı şekilde 7.11 denklemi de bu durumda.

**Kontrol Değişkenine göre Karar Verme Metodu (*Per-decision Methods with Control Variates) başlığı için:**
1.  Mesela bu başlıktaki ilk denkleme kitaptaki numarayı vermişsiniz sonrakilere vermemişsiniz. Burda hangisini yapacağımıza bir karar verip ona göre hepsini aynı formatta tutmakta fayda var.
2.  _Bunun yerine, bu daha sofistike yaklaşımda, h horizonda n−adım dönüş alternatif, politika dışı tanımını kullanır_ diye bir cümle var **horizon**'a konuya uygun çeviri yapmak gerek sanki.

**Önem Örneklemesiz Politika Dışı Öğrenme: n-adım Ağaç Yedekleme Algoritması (Off-policy Learning Without Importance Sampling: The n-step Tree Backup Algorithm) başlığı için:**
1. "3 aşamalı ağaç yedekleme..."  diye başlayan paragrafta ilk noktadan sonra büyük harfle başlanmamış. 

**Birleştirici Algoritma: n-adım Q (σ) Unifying Algorithm: n-step Q(σ) başlığı için:**
1. Bazı başlıklarda İngilizcesini parantez içinde yazmıştınız. Aynı şekilde mi devam edilse? 
2. Hemen giriş cümlesinde **Ağaç Yedeklemesi( Tree backup)** iki kelime arasındaki boşluk yanlış yerde durduğu için çok dikkat çekiyor.
3. **alacaktı. Ve** Yeni cümle **Ve** ile başlamaz onu silebiliriz.
4.Özet başlığından önceki denklermleri bir gözden geçirsek iyi olur. Resim hali de kalmış.

**Özet başlığı için:**
1. 2. paragrafın 2. cümlesi _Sağdaki iki 4 adımlı yedekleme diyagramı, sunulan yöntemlerin çoğunu birlikte özetler._  **Sağdaki** derken?

-- N'ler n olsun tüm sayfada!
Ellerinize sağlık 👍

**Comment by eralpozcan** [comment]
- **n-Adım Paketleme**
  - [x] 1.Madde : _Düzeltildi._
- **n-Adım TD Tahmin**
  - [x] 1.Madde : _Değiştirildi._
  - [x] 2.Madde : _Invisible kalmış düzeltildi._
  - [x] 3.Madde : _Monte Carlo olarak değiştirdim._
- **n−step Sarsa**
  - [x] 1.Madde : _"Step" Adım olarak değiştirildi._
  - [x] 2.Madde : _Bölüm 5'ten itibaren öyle yapılmaya başlandı. Tüm yazılarda uyarlanacak._
- **n− step Politika dışı (Off-Policy) Öğrenme**
  - [x] 1.Madde : _Düzeltildi._
  - [x] 2.Madde : _Denklemlerin atıfları eklendi._
  - [x] 3.Madde : _ 👍 ._
- **Kontrol Değişkenine göre Karar Verme Metodu**
  - [x] 1.Madde :  _Denklemlerin atıfları eklendi.__
  - [x] 2.Madde :  _Çevirisi düzeltildi._
- **Önem Örneklemesiz Politika Dışı Öğrenme: n-adım Ağaç Yedekleme Algoritması**
  - [x] 1.Madde :  _Harf hatası düzeltildi.__

- **Birleştirici Algoritma: n-adım Q (σ) Unifying Algorithm:**
  - [x] 1.Madde :  _İngilizcesi artık parantez içerisinde.__
  - [x] 2.Madde :  _Boşluk hatası düzeltildi.__
  - [x] 3.Madde :  _Ve kaldırıldı.__
  - [ ] 4.Madde :  _Arada bulunan açıklama Türkçeye çevirisi yapılıp resim hali kaldırıldı.__
- **Özet**
  - [x] _Şekil 7.5 olarak düzeltildi._

 _Düzeltmeler toplu olarak gönderilecek_

**Comment by eralpozcan** [comment]
Düzeltmeler yapıldığı için kapatıyorum. #33
