### ISSUE TITLE
Projeler altında Predictive Maintenance Blog URL hatalı

### ISSUE THREAD

**Issue by kivancguckiran** [yz-ai/yz-ai.github.io#16]
https://github.com/yz-ai/yz-ai.github.io/blob/master/_data/projects.yml

Projeler altında "Predictive Maintenance of Aircraft Motor Health with LSTM" başlığının altındaki blog url Teknofest projesindeki gibi kalmış.

**Comment by kivancguckiran** [comment]
@ayyucekizrak Blog yazısı var mıydı? Yoksa kaldırılacak mı blog linki?

**Comment by yavuzKomecoglu** [comment]
Yanlışlıkla öle kalmış. Blog linkini kaldırdım.

https://github.com/yz-ai/yz-ai.github.io/commit/2f8e2b122d9af8cc74b866f0503c4f48d0195902
