### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 8: Tabular Metotlar

### ISSUE THREAD

**Issue by ayyucekizrak** [yz-ai/yz-ai.github.io#23]
Pekiştirmeli Öğrenme - Bölüm 8: Tabular Metotlar
https://yz-ai.github.io/blog/pekistirmeli-ogrenme/tabular-metotlar-bolum-8

---

**Başlık altı yazısı için:** 
_"Modele dayalı yöntemler, temel bileşen olarak planlama yapmaya dayanırken, model içermeyen yöntemler temel olarak öğrenmeye dayanır. Bu iki yöntem arasında farklılıklar ve benzerlikler vardır. Özellikle, her iki yöntemin temelin de , değer fonksiyonlarının hesaplanması vardır. Bu bölümdeki amacımız, model tabanlı ve modelsiz yöntemlerin birleştirilmesidir (integration)."_

Bu cümleyi anlamını koruyarak yeniden yazıyorum: 

_Bu iki yöntemin benzer ve farklı yanları vardır. En önemli farklılıkları; model gerektiren yöntemlerin temel bileşeni planlama iken model içermeyen yöntemlerin öğrenmeye dayalı bir temel bileşene sahip olmasıdır. En önemli benzerlikleri ise, değer fonksiyonlarının hesaplama gereksinimleridir. Bu bölümdeki amacımız model gerektiren ve model içermeyen yöntemlerin birleştirilmesidir (integration)._

Bu lafın aynısı **Planlama ve Tabular Metotlar ile Öğrenme** başlığı altında da geçiyor.

**Modeller ve Planlama başlığı için:** 
1. Dağıtım modeli (distribution model) : buna emin miyiz genellikle **dağılım** denir. RL de dağıtım deniyorsa kalsın tabi.
2. _simülasyon etmek_ yerine _simüle etmek_ daha iyi olur gibi.
3. Model→Taklitdeneyimi→Değerler→Politika  kısmı çok güzel ama önündeki ve arkasındaki satırdan ayırıp tek başına yani iki paragraf arasında bırakmak daha güzel görünebilir. Bir de _Taklit Deneyimi_ arasına bir boşluk :)

**Dyna: Entegre Planlama, Oyunculuk (Acting) ve Öğrenme başlığı için:**
1. ilk kullanılan şeklin üstündeki yazının harflerinden sarkan kuyturklar görünüyor tekrar üst kısmı kesilde bide şekil sayfada ortalanabiliyorsa süper olur. Bir de şekilde "acting" ingilizce kalmış.
2. Bu başlık altında da  _simülasyon edilmiş_ diye geçiyor.
3. (Direct RL) her seferinde parantez içinde verilmeli mi emin olamadım. Ama kalabilir herkes tüm kitabı okumayabilir karşılaşınca görsün. (yazılı düşündüm :) )
4. Örneğin, Şekil 8.2’de diye başlayan paragrafın altındaki şeklin öyle bir numarası yok burda kitaptaki numarasına atıf verince kafalar karışıyor. Aşağıdaki şekil diyip parantez içinde de kitaptaki 8.2 gibi bi atıflama yoluna mı gitsek acaba.
5. Aynı şekil iki kez eklenmiş (Türkçe ve İng. olarak) ve arasına _% kontrol edilmeli_ yazılmış bilginize.
6. "E_ylemler arasında açgözlü( greedily) seçerken, bağlar rastgele kırıldı. Ajanların, planlama adımlarının sayısı da değişti."_ kırılır ve değişir desek daha iyi. 
7. Şekil 8.3 denen yer içinde şekil atıfları konusunu düşünmek gerek.
8. Son şekilde hem Türkçe hem İngilizce olarak duruyor.
9. Son paragrafta yine simülasyon edilmiş demişiz.

**Model Yanlış Olduğunda başlığı için:**
1.  _"Model boş başladı ve daha sonra sadece tam olarak doğru bilgilerle dolduruldu. Genel olarak, bu kadar şanslı olmayı bekleyemeyiz. Modeller yanlış olabilir, çünkü ortam stokastiktir ve sadece sınırlı sayıda örnek gözlemlenmiştir, ya da model, kusurlu bir şekilde genelleştirilen fonksiyon yaklaşımı kullanılarak ya da çevrenin değiştiği ve yeni davranışının henüz gözlemlenmediği için öğrenilmiştir. Model yanlış olduğunda, planlama sürecinin optimal bir politika oluşturması muhtemeldir."_ 
Bu paragrafı yeniden yazıyorum:
_ Boş olarak başlayan model ve sonrasında sadece doğru bilgilerle doldurulur desek de genel olarak bu kadar şanslı olmayı beklemeyiz. Ortam stokastiktir ve sadece sınırlı sayıda örnek ile gözlemlenmektedir. Bu yüzden model yanlış olabilir. Model yanlış demek; kusurlu şekilde genelleştiren fonksiyon yaklaşımı kullanılması ya da çevrenin değiştiği için yeni davranışın henüz gözlemlenmediği öğrenilmiştir. Model yanlış olduğunda planlanma sürecinin optimal bir politika oluşturması muhtemeldir._

2. İkinci paragrafın sondan bir önceki cümlesinin noktası yok.
3. Şekil İngilizce kalmış.

**Öncelikli Süpürme başlığı için:** 
1. ilk paragrafta simülasyon edilmiş demişiz yine.
2. Savurgan güncelleme ? Parantez içinde ingilizcesini de verelim.
3. İkinci paragraftan _"Tipik olarak, bu, diğer birçok durumun değerlerinin de değiştirilmesi gerektiği anlamına gelecektir, ancak tek yararlı tek adım güncellemeleri, değeri değiştirilmiş olan tek bir duruma yönlendiren eylemlerdir. Bu eylemlerin değerleri güncelleştirilirse, önceki durumların değerleri sırayla değişebilir. Öyleyse, bunları yönlendiren işlemlerin güncellenmesi gerekiyor ve ardından önceki durumlar değişmiş olabilir."_
Yeniden yazıyorum:
_Tipik olarak, diğer birçok durumun değerinin değiştirilmesi gerektiği anlamını taşır. Ancak yararlı olacak tek adım güncellemeleri, değeri değiştirilmiş olan yalnız bir duruma yönlendiren eylemlerdir. Bu eylemlerin değerleri güncellenirse, önceki durumların değeri de sırayla değişebilir olacaktır. Öyleyse, bunları yönlendiren işlemlerin güncellenmesi gerekmektedir ve böylece önceki durumlar da değişmiş olur._
4. Paragraf 3te _etki hesaplanır. etki, küçük eşikten_ noktadan sonra büyük harf lütfen :)
5. Son paragrafta bu cümleyi yeniden yazmak gerek. _"Bu bölümde, her türlü durum alanı planlamasının, yalnızca güncellemenin türü, büyük, küçük ya da küçük ve güncellemelerin yapıldığı sıraya göre değişen değer güncellemeleri dizileri olarak görülebileceğinin önermesini gördük."_
Şu şekilde yazıyorum: 
_Bu bölümde, tüm durumların alan planlaması yalnızca güncellemenin türü, büyük ya da küçük güncellemelerin yapıldığı sıraya göre değişen değer dizileri olarak görülemeyeceğinin önermesini inceledik._

**Beklenen ve Örnek Güncellemeler başlığı için:**
1. Bu başlıktaki şekiller İngilizce kalmış.
2. İlk cümledeki  **q, v, q ve v** bir kontrol edilsin. İndisleri yazılmamış sanırım.
3. % Kontrol yazılmış (kendinize not sanırım)
4. Yine şekil 8.7 denmiş şekil atıfını bir yola koymak gerek.

**Yörünge Örneklemesi m başlığı için:**
1. Bu başlıkta da şekiller İngilizce.
2. İkinci paragraf _simülasyon etmek_
3. Mesela burada da şekillere hiç atıf verilmemiş.

**Gerçek Zamanlı Dinamik Programlama başlığı için:**
1. Bu başlık altındaki kitaptaki ilk şekil eklenebilir güzel bir anlatımı var.
2. İlk paragrafta zaten kitaptaki 8.8 şekline atıf cümle var ama şekil yok.

**Karar Zamanında Planlama başlığı için:**
1. Bu başlık altında da simülasyon edilmiş şeklinde kullanılmış.

**Sezgisel Arama başlığı için:**
1. Şekil 8.9 denmiş olan paragrafın altındaki şekil ifade edilmek isteniyor sanırım

**Rollout Algoritmaları başlığı için:** bu kısım çok güzel yazılmış.

**Monte Carlo Arama Ağacı başlığı için:**
1. Monte Carlo Arama Ağacı (MCTS) ingilizce kısaltmasını açık hali de parantezin içinde bi seferlik verilebilir. _(Monte Carlo Tree Search-MCTS)_

---

Elinize sağlık 👍

**Comment by eralpozcan** [comment]
- **Başlık altı yazısı**
  - [x] 1. : _Düzeltildi._
- **Modeller ve Planlama başlığı :**
  - [ ] 1. : _Bunu sonraya bıraktım._
  - [x] 2. : _simüle etmek olarak cümle düzeltildi._
  - [x] 3. : _Düzelttim "ğ" de font tipinden ötürü sorun var daha sonra düzelteceğim._
- **Dyna: Entegre Planlama, Oyunculuk (Acting) ve Öğrenme**
  - [x] 1. : _Eksik yerleri düzeltilip güncellendi._
  - [x] 2. : _simüle etmek olarak cümle düzeltildi._
  - [x] 3. : _Önceki konularda tek yerde gösterdiğimiz için burayı da öyle yapıyorum._
  - [x] 4. : _Şekillerin aslında isimleri var ancak manuel olarak tekrar eklemek gerekiyor. 😢_
  - [x] 5. : _Türkçe çevirisinin doğruluğunun kontrolü için not düşmüştüm.Sanırım sıkıntı yok. 🙄_
  - [x] 6. : _Dediğiniz gibi düzeltim._
  - [x] 7. : _Artık atıflar kitaptaki gibi._
  - [x] 8. : _Kaldırdım._
  - [x] 9. : _Tüm yazıda düzelttim._
- **Model Yanlış Olduğunda başlığı**
  - [x] 1. : _Dediğiniz gibi değiştirdim._
  - [x] 2. : _Ekledim_
  - [x] 3. : _Türkçeye çevirip ekledim.Atıflarını ekledim._

- **Öncelikli Süpürme başlığı**
  - [x] 1.:_Tüm yazıda düzeltmiştim.Önceki maddelerden ötürü._ 
  - [x] 2.:_Kitapta "wasteful" kullanılmış cümlede eklendi._
  - [x] 3.:_Yazdığınız ile değiştirdim._
  - [x] 4.:_ 👍 ._
  - [x] 5.:_Yazdığınız ile değiştirdim._

- **Beklenen ve Örnek Güncellemeler**
  - [ ] 1.: _Düzeltip kaldırdım fazla olanı. Alt bilgi yazısını ekledim ._
  - [x] 2.: _Düzelttim._
  - [x] 3.: _Düzelttim._
  - [x] 4.: _Şekil artık kitaptaki ile aynı._

- **Yörünge Örneklemesi**
  - [x] 1.: _Şekiller düzeltildi ve alt yazısı eklendi._
  - [x] 2.: _Tüm yazıda düzeltildi._
  - [x] 3.: _Şekiller düzeltildi ve atıfları verildi._
- **Gerçek Zamanlı Dinamik Programlama**
  - [x] 1.: _Eklendi.Yüklemesi yapılınca görünür olacak._
  - [x] 2.: _Atıflar düzeltildi._
- **Karar Zamanında Planlama**
  - [x] 1.: _Düzelttim._
- **Sezgisel Arama**
  - [x] 1.: _Düzeltildi._
- **Rollout Algoritmaları**
  _TAM NOT ALINDI. 💯_
- **Monte Carlo Arama Ağacı**
  - [x] 1. : _Dediğiniz gibi ekledim._


_Eksikleri tamamlanınca güncelleyeceğim. Elinize sağlık hocam_

**Comment by eralpozcan** [comment]
Güncellemesi yapıldığı için kapatıyorum. Elinize sağlık 👍
