### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 9: Yaklaşıklama İle Politikalı Öngörü

### ISSUE THREAD

**Issue by ayyucekizrak** [yz-ai/yz-ai.github.io#27]
https://yz-ai.github.io/blog/pekistirmeli-ogrenme/on-policy-prediction-bolum-9#what-is-doks

---

**Değer Öngörüsü (Value Prediction) başlığı için:**
1. son cümlede "gradyen" yazmışız gradyan demiyor muyuz? Eğer siz böyle karar verdiyseniz sorun yok. Bundan sonra da aynı kelime için eğer kara değişirse ona göre düzeltme gerekcek.

**Doğrusal Yöntemler başlığı için:**
1. Son cümlede "öz nitelik" yazılmış bitişik olmalı feature dan bahsediyorsak.

**Bellek Tabanlı Fonksiyon Yaklaşıklığı başlığı için:**
1.ikinci paragrafta "bir-çok" ayrı yazılmış bitişik olmalı.

**Kernel Tabanlı Fonksiyon Yaklaşıklığı başlığı için:**
1. Kernel durabilir beli çekirdek te denebilir.

---
Elinize sağlık bu o kadar zorlamamış oldu 👍

**Comment by eralpozcan** [comment]
Güncelledim. Elinize sağlık hocam 👍
