### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 10: On-policy Control With Approximation

### ISSUE THREAD

**Issue by ayyucekizrak** [yz-ai/yz-ai.github.io#28]
https://yz-ai.github.io/blog/pekistirmeli-ogrenme/on-policy-control-bolum-10
---

**Episodik Yarı-Gradyan Kontrolü başlığı için:**
1. "Mountain Car Görevi" başlığında karakterlerde bi gariplik var sanki.
2. şekil ing. ama kötü görünmüyor kalabilir.

**N-adımlı Yarı-Gradyen Sarsa başlığı için:**
1. formüller iki kez yazılmış (ikinciler resim sanıırm silinmesi gerek)
2.episodic gösterimini ingilizce bırakmayalım bence

**Diferansiyel Yarı-Gradyende n−adımlı Sarsa başlığı için:** 
1. burdaki algoritma tablosu da ingilizce olmasın bence.

---
Elinize sağlık 💯

**Comment by eralpozcan** [comment]
**Episodik Yarı-Gradyan Kontrolü başlığı için:**
 - [x] 1. Çözüldü.
 - [x] 2. Çevirisi yapıldı.

**N-adımlı Yarı-Gradyen Sarsa başlığı için:**
 - [x] 1.Çözüldü.
 - [ ] 2. Çevirisi yapıldı.

**Diferansiyel Yarı-Gradyende n−adımlı Sarsa başlığı için:**
 - [ ] 1. Çevirisi yapıldı.

**Comment by eralpozcan** [comment]
Algoritmaların çevirisi dışında hepsi yapıldı.
Algoritmalar geçici olarak daha sonra yapılacak

Teşekkürler ayyüce hocam :)
