### ISSUE TITLE
Pekiştirmeli Öğrenme - Bölüm 3: Sonlu Markov Karar Süreçleri

### ISSUE THREAD

**Issue by basakbuluz** [yz-ai/yz-ai.github.io#6]
https://github.com/yz-ai/yz-ai.github.io/blob/master/_posts/2019-01-03-sonlu-markov-karar-surecleri-bolum-3.md

**Ajan-Çevre Arayüzü (The Agent-Environment Interface) başlığı için** 

1. ilk paragrafın son cümlesinde 'izlek' yerine 'yörünge' kullanmak daha anlaşılır olur diye düşünüyorum.
2. ikinci paragrafın ilk cümlesinde 'durum, eylem ve ödül setlerinin' yerine 'kümelerinin' mi desek?
3. 'ayrık bir olasılık dağılımına' yerine 'ayrık bir olasılık dağılıma'
4. 'Sonuç olarak,' yerine 'Sonuç olarak;'

**Hedefler ve Ödüller (Goals and Rewards) başlığı için** 
1. 'Ajanın, seçtiği eylemler sonucunda elde ettiği ödül, genellikle sayısal bir değer olmaktadır' cümlesindeki 2 virgüle de ihtiyaç yok.
2. 'Bir hedefi formüle etmek için ödül sinyalinin kullanılması, Pekiştirmeli Öğrenme’‘nin ayırt edici özelliklerinden biridir.' yerine 'Bir hedefi formüle etmek için ödül sinyalinin kullanılması Pekiştirmeli Öğrenme’nin ayırt edici özelliklerinden biridir.'
3. 'Ödül vesilesiyle, ajana yaptırılmak istenenin nasıl elde edilebileceğine dair önceden bilgi verilmesine gerek yoktur.' cümlenin ne demek istediği tam anlaşılmıyor, konuya hakim olmadığım için öneride bulunamadım ama bu cümlenin üzerinden geçilmeli.
4. 'Örneğin satranç oynayan bir oyuncu, kazanmak için ödüllendirilmelidir fakat ..' yerine 'Örneğin, satranç oynayan bir oyuncu kazanmak için ödüllendirilmelidir fakat..'

**Getiriler ve Bölümler (Returns and Episodes) başlığı için**  
1. Bölüm başlığında episodes için 'olay' kullanılsa daha anlaşılır olabilir mi?
2. 'Ajanın eylemlerinden aldığı ödüller, Rt,Rt+1,Rt+2,⋯, olarak belirtilirse,' yerine 'Ajanın eylemlerinden aldığı ödüller Rt,Rt+1,Rt+2,⋯ olarak belirtilirse'
3.  'Ajan-Çevre etkileşimi, bölüm (episode) olarak isimlendirilen bir çok durum ve eylem serilerinden oluşan ve uç durum denilen özel bir durum ile sona eren bir yapı ile sağlanmaktadır ve her bölüm sonunda durum tekrar başlangıç durumuna getirilir.' yerine 'Ajan-Çevre etkileşimi, bölüm (episode) olarak isimlendirilen bir çok durum ve eylem serilerinden oluşan, uç durum denilen özel bir durum ile sona eren bir yapı ile sağlanmaktadır ve her bölüm sonunda durum tekrar başlangıç durumuna getirilmektedir.'
4. 'Bir çok farklı problem içerisindeki ajan-çevre etkileşiminde ise, yapı bölümlerden oluşmayabilir.' yerine 'Bir çok farklı problem içerisindeki Ajan-Çevre etkileşiminde ise yapı bölümlerden oluşmayabilir.'

**Bölümlü ve Bölümsüz Problemler için Birleşik Notasyon (Unified Notation for Episodic and Continuing Tasks) başlığı için** 
1. 'Önceki kısımlarda, ajan-çevre etkileşimin ..' yerine 'Önceki kısımlarda, ajan-çevre etkileşimi '
2. 'Bölümlü problemler matematiksel olarak daha kolay olmaktadır zira her bir..' yerine 'Bölümlü problemler matematiksel olarak daha kolay olmaktadır, zira her bir..'
3. 've her iki durum eş zamanlı olarak sembolize edilebilecek' yerine 've her iki durumu eş zamanlı olarak sembolize edilebilecek'
4. 'Hem bölümlü hem de bölümsüz problemleri kapsayan tek bir gösterim elde etmek için başka bir yönteme ihtiyaç duyulmaktadır. Denklem 3.1 getiriyi sınırlı sayıda terim üzerinden, Denklem 3.2 ise sonsuz sayıda terim üzerinden hesaplamaktadır. Bu iki denklem, yalnızca kendisine geçiş yapan ve sıfır ödül üreten özel bir durduran durumun kullanılması ile birleştirilebilir. Bu gösterimin diyagramı Şekil 3.2’de görülebilir.' paragrafı 2 kez yer alıyor ve başlık formatında gözüküyor şuan.

**Politikalar ve Değer Fonksiyonları (Policies and Value Functions) başlığı için** 
1. 'İdealde, π politikasına bağlı olarak erişilen herhangi bir durumdaki getiri, durum değer fonksiyonunun tahminine, seçilen eylem sonrasında hesaplanan getiri de, eylem değer fonksiyonunun tahminlemesine eşit olmalıdır.' yerine 'İdealde π politikasına bağlı olarak erişilen herhangi bir durumdaki getiri, durum değer fonksiyonunun tahminine; seçilen eylem sonrasında hesaplanan getiri de, eylem değer fonksiyonunun tahminlemesine eşit olmalıdır.'

**En Uygunluk Ölçütü ve Yaklaşım (Optimality and Approximation) başlığı için** 
1. 'Ortam dinamiklerinin doğru ve tam bir modeline sahip olunsa dahi, Bellman uygunluk eşitliği en uygun politikayı hesaplamak genellikle mümkün olmaz.' yerine 'Ortam dinamiklerinin doğru ve tam bir modeline sahip olunsa dahi, Bellman uygunluk eşitliği ile en uygun politikayı hesaplamak genellikle mümkün olmaz.'
2. 'Bu sebeple, problemlere belli hata payları ile yaklaşıklıklar ile yapılmaktadır. İşe yarar bir politikanın, en uygun politika olmamakla beraber belli bir kriter içerisinde seyretmesi, kullanılabilir bir yapıya dönüşebilir.' yerine 'Bu sebeple, problemlere belli hata payları ile yaklaşıklıklar **(yaklaşımlar da olabilir sanki?)** yapılmaktadır. İşe yarar bir politika, en uygun politika olmamakla beraber belli bir kriter içerisinde seyretmesi ile, kullanılabilir bir yapıya dönüşebilir.'
3. 'Pekiştirmeli öğrenmenin çevrimiçi (online) yapısı, daha az sıklıkla karşılaşılan durumlara daha az efor sarf etme pahasına, sıkça karşılaşılan durumlarda daha iyi kararlar alması için en uygun politikaya yaklaşım yaptırmaya imkan sağlar. ' yerine 'Pekiştirmeli öğrenmenin çevrimiçi (online) yapısı; daha az sıklıkla karşılaşılan durumlara daha az efor sarf ederek, sıkça karşılaşılan durumlarda daha iyi kararlar alması için en uygun politikaya yaklaşım yaptırmaya imkan sağlar. '

**Comment by eralpozcan** [comment]
Düzeltmeler çok önce yapıldığından kapatıyorum. Elinize sağlık
